version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "9906:3306"
  php:
    container_name: php
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/var/www/html